drop table if exists `move_function`;

create table `move_function` (
	`code` text primary key,
	`desc` text not null check (`desc` != '')
) without rowid;

insert into `move_function` (`code`, `desc`)
values
('000', 'No additional effect.'),
('001', 'Does absolutely nothing.'),
('002', 'Ignores type effectiveness. User takes 25% of max HP as recoil damage.'),
('003', 'Inflicts sleep.'),
('004', 'Inflicts sleep one turn after use.'),
('005', 'Inflicts poison.'),
('006', 'Inflicts bad poison.'),
('007', 'Inflicts paralysis.'),
('008', 'Inflicts paralysis. Hits Pokémon using Fly, Bounce or Sky Drop. Has perfect accuracy in rain, but 50 accuracy in sun.'),
('009', 'Inflicts paralysis and flinch.'),
('00A', 'Inflicts burn.'),
('00B', 'Inflicts burn and flinch.'),
('00C', 'Inflicts freeze.'),
('00D', 'Inflicts freeze. Has perfect accuracy in hail.'),
('00E', 'Inflicts freeze and flinch.'),
('00F', 'Inflicts flinch.'),
('010', 'Inflicts flinch. Does double damage if target has used Minimize.'),
('011', 'Inflicts flinch. Fails unless user is asleep.'),
('012', 'Inflicts flinch. Fails unless it''s the user''s first turn on the field.'),
('013', 'Inflicts confusion.'),
('014', 'Inflicts confusion, but only if user is Chatot. Chance depends on the volume of Chatot''s cry.'),
('015', 'Inflicts confusion. Hits Pokémon using Fly, Bounce or Sky Drop. Has perfect accuracy in rain, but 50 accuracy in sun.'),
('016', 'Inflicts infatuation.'),
('017', 'Inflicts burn, freeze or paralysis.'),
('018', 'Cures user of burn, poison and paralysis.'),
('019', 'Cures all Pokémon in party of permanent status conditions.'),
('01A', 'Prevents Pokémon on the user''s side from being inflicted with status conditions.'),
('01B', 'Passes the user''s permanent status condition to the target.'),
('01C', 'Increases user''s Attack by 1 stage.'),
('01D', 'Increases user''s Defense by 1 stage.'),
('01E', 'Increases user''s Defense by 1 stage and curls user up (increasing power of Rollout).'),
('01F', 'Increases user''s Speed by 1 stage.'),
('020', 'Increases user''s Special Attack by 1 stage.'),
('021', 'Increases user''s Special Defense by 1 stage and doubles the power of the user''s next move if it is Electric-type.'),
('022', 'Increases user''s evasion by 1 stage.'),
('023', 'Increases user''s critical hit rate.'),
('024', 'Increases user''s Attack and Defense by 1 stage.'),
('025', 'Increases user''s Attack, Defense and accuracy by 1 stage.'),
('026', 'Increases user''s Attack and Speed by 1 stage.'),
('027', 'Increases user''s Attack and Special Attack by 1 stage.'),
('028', 'Increases user''s Attack and Special Attack by 1 stage, or 2 stages in sun.'),
('029', 'Increases user''s Attack and accuracy by 1 stage.'),
('02A', 'Increases user''s Defense and Special Defense by 1 stage.'),
('02B', 'Increases user''s Special Attack, Special Defense and Speed by 1 stage.'),
('02C', 'Increases user''s Special Attack and Special Defense by 1 stage.'),
('02D', 'Increases every stat of the user except HP, accuracy and evasion by 1 stage.'),
('02E', 'Increases user''s Attack by 2 stages.'),
('02F', 'Increases user''s Defense by 2 stages.'),
('030', 'Increases user''s Speed by 2 stages.'),
('031', 'Increases user''s Speed by 2 stages and halves the user''s weight.'),
('032', 'Increases user''s Special Attack by 2 stages.'),
('033', 'Increases user''s Special Defense by 2 stages.'),
('034', 'Increases user''s evasion by 2 stages and minimizes the user.'),
('035', 'Increases user''s Attack, Speed and Special Attack by 2 stages but decreases user''s Defense and Special Defense by 1 stage.'),
('036', 'Increases user''s Speed by 2 stages and Attack by 1 stage.'),
('037', 'Increases a random stat of the user other than HP, including accuracy and evasion, by 2 stages.'),
('038', 'Increases user''s Defense by 3 stages.'),
('039', 'Increases user''s Special Attack by 3 stages.'),
('03A', 'Maximises user''s Attack but removes 50% of user''s max HP.'),
('03B', 'Decreases user''s Attack and Defense by 1 stage.'),
('03C', 'Decreases user''s Defense and Special Defense by 1 stage.'),
('03D', 'Decreases user''s Defense, Special Defense and Speed by 1 stage.'),
('03E', 'Decreases user''s Speed by 1 stage.'),
('03F', 'Decreases user''s Special Attack by 2 stages.'),
('040', 'Increases target''s Special Attack by 1 stage, but confuses them.'),
('041', 'Increases target''s Attack by 2 stages, but confuses them.'),
('042', 'Decreases target''s Attack by 1 stage.'),
('043', 'Decreases target''s Defense by 1 stage.'),
('044', 'Decreases target''s Speed by 1 stage.'),
('045', 'Decreases target''s Special Attack by 1 stage.'),
('046', 'Decreases target''s Special Defense by 1 stage.'),
('047', 'Decreases target''s accuracy by 1 stage.'),
('048', 'Decreases target''s evasion by 1 stage.'),
('049', 'Decreases target''s evasion by 1 stage, removes all barriers on the target''s side, and removes any entry hazards from the field.'),
('04A', 'Decreases target''s Attack and Defense by 1 stage.'),
('04B', 'Decreases target''s Attack by 2 stages.'),
('04C', 'Decreases target''s Defense by 2 stages.'),
('04D', 'Decreases target''s Speed by 2 stages.'),
('04E', 'Decreases target''s Special Attack by 2 stages, if their gender is opposite to the user.'),
('04F', 'Decreases target''s Special Defense by 2 stages.'),
('050', 'Resets target''s stat changes.'),
('051', 'Resets stat changes for all Pokémon on the field.'),
('052', 'Swaps user''s and target''s Attack and Special Attack changes.'),
('053', 'Swaps user''s and target''s Defense and Special Defense changes.'),
('054', 'Swaps user''s and target''s stat changes.'),
('055', 'Copies target''s stat changes to user.'),
('056', 'Adds a barrier to the user''s side which prevents lowering of stats.'),
('057', 'Swaps user''s Attack and Defense.'),
('058', 'Averages user''s and target''s Attack and Special Attack.'),
('059', 'Averages user''s and target''s Defense and Special Defense.'),
('05A', 'Averages user''s and target''s current HP.'),
('05B', 'Adds an effect to the user''s side which doubles Speed.'),
('05C', 'Turns into the last move used by the target. Effect is removed when user leaves the field.'),
('05D', 'Permanently replaces itself with the last move used by the target.'),
('05E', 'Changes user''s type to that of a randomly-chosen move of the user other than this one.'),
('05F', 'Changes user''s type to a random type that resists the last attack used by the target.'),
('060', 'Changes user''s type to one depending on the environment.'),
('061', 'Makes target Water-type.'),
('062', 'Makes user same type as target.'),
('063', 'Makes target''s ability Simple.'),
('064', 'Makes target''s ability Insomnia.'),
('065', 'Makes user have same ability as target.'),
('066', 'Makes target have same ability as user.'),
('067', 'Swaps user''s and target''s abilities.'),
('068', 'Negates effect of target''s ability.'),
('069', 'Transforms user into target.'),
('06A', 'Does fixed 20 HP damage.'),
('06B', 'Does fixed 40 HP damage.'),
('06C', 'Halves target''s current HP.'),
('06D', 'Does fixed damage equal to user''s level.'),
('06E', 'Does fixed damage to make the user''s and target''s current HP equal.'),
('06F', 'Does fixed damage equal to between 0.5 and 1.5 times the user''s level, randomly determined.'),
('070', 'Deals a one-hit KO. Accuracy depends on difference between the user''s and target''s levels (higher user level = more accuracy, lower target level = more accuracy).'),
('071', 'If a physical move was used against the user this turn, deals 2x the damage from that move to the target.'),
('072', 'If a special move was used against the user this turn, deals 2x the damage from that move to the target.'),
('073', 'If a damaging move was used against the user this turn, deals 1.5x the damage from that move to the target.'),
('074', 'Damages ally for 1/16 of their max HP.'),
('075', 'Hits target using Dive with double the power.'),
('076', 'Hits target using Dig with double the power.'),
('077', 'Hits target using Bounce, Fly or Sky Drop with double the power.'),
('078', 'Hits target using Bounce, Fly or Sky Drop with double the power. Inflicts flinch.'),
('079', 'Has double power if target has used Fusion Flare this turn.'),
('07A', 'Has double power if target has used Fusion Bolt this turn.'),
('07B', 'Has double power if target is poisoned.'),
('07C', 'Has double power if target is paralyzed, but cures paralysis.'),
('07D', 'Has double power if target is asleep, but cures sleep.'),
('07E', 'Has double power if user is burned, poisoned or paralyzed.'),
('07F', 'Has double power if target is inflicted with a status condition.'),
('080', 'Has double power if target has no more than half of its max HP remaining.'),
('081', 'Has double power if user has been damaged by target''s move this turn.'),
('082', 'Has double power if target has already lost HP this turn.'),
('083', 'Has double power if ally has already used this move this turn, and hits directly after the ally''s move, ignoring priority.'),
('084', 'Has double power if target has already moved this turn.'),
('085', 'Has double power if a teammate fainted last turn.'),
('086', 'Has double power if user does not hold an item.'),
('087', 'Has double power in weather, with type depending on the type of weather.'),
('088', 'Hits target switching out with double the power.'),
('089', 'Power increases with user''s happiness.'),
('08A', 'Power decreases with user''s happiness.'),
('08B', 'Power increases with user''s HP.'),
('08C', 'Power increases with target''s HP.'),
('08D', 'Power increases the faster the target is compared to the user.'),
('08E', 'Power increases the more positive stat changes the user has.'),
('08F', 'Power increases the more positive stat changes the target has.'),
('090', 'Power and type depend on the user''s IVs.'),
('091', 'Power doubles with each consecutive use.'),
('092', 'Power increases with each consecutive use.'),
('093', 'Inflicts rage on the user, which increases their Attack by 1 stage every time they are damaged by a move.'),
('094', 'Randomly damages or heals the target.'),
('095', 'Power is randomly chosen. Hits target using Dig with double the power.'),
('096', 'Power and type depend on the user''s held berry, which is consumed.'),
('097', 'Power increases as this move''s PP decreases.'),
('098', 'Power decreases with user''s HP.'),
('099', 'Power increases the faster the user is compared to the target.'),
('09A', 'Power increases with the target''s weight.'),
('09B', 'Power increases the heavier the user is compared to the target.'),
('09C', 'Increases power of ally''s move by 1.5x for this turn.'),
('09D', 'Weakens Electric-type attacks.'),
('09E', 'Weakens Fire-type attacks.'),
('09F', 'Type depends on the user''s held item.'),
('0A0', 'Always critically hits.'),
('0A1', 'Adds an effect to the user''s side preventing critical hits from opponents.'),
('0A2', 'Adds a barrier to the user''s side halving power of physical moves used by opponents.'),
('0A3', 'Adds a barrier to the user''s side halving power of special moves used by opponents.'),
('0A4', 'Effect depends on environment.'),
('0A5', 'Never misses.'),
('0A6', 'Ensures that the user''s next move against the target will not miss.'),
('0A7', 'Makes any subsequent moves used by the user on the target ignore the target''s evasion change, and ignore the immunities of the Ghost type.'),
('0A8', 'Makes any subsequent moves used by the user on the target ignore the target''s evasion change, and ignore the immunities of the Dark type.'),
('0A9', 'Ignores target''s Defense, Special Defense and evasion changes.'),
('0AA', 'Protects the user from moves used by opponents.'),
('0AB', 'Protects the user''s side from priority moves.'),
('0AC', 'Protects the user''s side from multi-target moves.'),
('0AD', 'Hits protected target, and removes their protection.'),
('0AE', 'Uses last move used by target.'),
('0AF', 'Uses last move used by Pokémon on the field.'),
('0B0', 'Uses move target is set to use this turn, with 1.5x the power.'),
('0B1', 'For the duration of the current turn, reflects status moves targeting user to their users.'),
('0B2', 'For the duration of the current turn, negates the effect of any positive stat-changing moves used by any Pokémon on the field, and applies their effects to the user instead.'),
('0B3', 'Uses a move depending on the environment.'),
('0B4', 'Uses a random move known by the user.'),
('0B5', 'Uses a random move known by a teammate (other than the user themselves).'),
('0B6', 'Uses a random move.'),
('0B7', 'Adds a temporary status condition to the target which prevents them from using the same move twice in a row.'),
('0B8', 'Adds a temporary status condition to the target which disables any moves known by the user.'),
('0B9', 'Adds a temporary status condition to the target which disables the last move they used.'),
('0BA', 'Adds a temporary status condition to the target which prevents them from using non-damaging moves.'),
('0BB', 'Adds a temporary status condition to the target which prevents them from using healing moves.'),
('0BC', 'Adds a temporary status condition to the target which forces them to repeat the last move used.'),
('0BD', 'Hits twice.'),
('0BE', 'Hits twice. Inflicts poison.'),
('0BF', 'Hits three times, with power depending on the number of hits.'),
('0C0', 'Hits a random number of times, between 2 and 5.'),
('0C1', 'Hits as many times as there are status-free teammates, with base power of each hit depending on the teammate''s Attack.'),
('0C2', 'User must recharge after successful use.'),
('0C3', 'User must wait a turn before use.'),
('0C4', 'User must wait a turn before use, except in sun. Power is halved in weather other than sun.'),
('0C5', 'User must wait a turn before use. Inflicts paralysis.'),
('0C6', 'User must wait a turn before use. Inflicts burn.'),
('0C7', 'User must wait a turn before use. Inflicts flinch.'),
('0C8', 'Increases user''s Defense by 1 stage on the first turn after use, then hits on the second turn.'),
('0C9', 'User must wait a turn before use, but is in the sky and invulnerable to most attacks during that turn.'),
('0CA', 'User must wait a turn before use, but is underground and invulnerable to most attacks during that turn.'),
('0CB', 'User must wait a turn before use, but is underwater and invulnerable to most attacks during that turn.'),
('0CC', 'User must wait a turn before use, but is in the sky and invulnerable to most attacks during that turn. Inflicts paralysis.'),
('0CD', 'User must wait a turn before use, but is invulnerable during that turn. Hits protected target and removes their protection.'),
('0CE', 'User must wait a turn before use. Both user and target are in the sky and invulnerable to most attacks during that turn; target is also unable to move. If target is airborne, does not deal damage.'),
('0CF', 'Traps target temporarily, dealing 1/16 max HP per turn.'),
('0D0', 'Traps target temporarily, dealing 1/16 max HP per turn. Hits target using Dive with double power.'),
('0D1', 'User is locked into this move for 2 more turns. No Pokémon on the field can sleep during this time.'),
('0D2', 'User is locked into this move temporarily, and is confused afterwards.'),
('0D3', 'User is locked into this move for 4 more turns, with power doubling with each successive hit, or if user has used Defense Curl.'),
('0D4', 'User waits two turns, then deals 2x the damage it received to the last Pokémon that damaged it.'),
('0D5', 'User heals by 1/2 max HP.'),
('0D6', 'User heals by 1/2 max HP and loses Flying-type for this turn.'),
('0D7', 'Pokémon in user''s position is healed by 1/2 max HP at the end of the next turn.'),
('0D8', 'User heals by an amount depending on the weather.'),
('0D9', 'User heals fully and falls asleep.'),
('0DA', 'Adds a temporary status condition to the user which heals them for 1/16 max HP per turn.'),
('0DB', 'Adds a temporary status condition to the user which heals them for 1/16 max HP per turn, but prevents them from leaving the field.'),
('0DC', 'Inflicts Leech Seed on the target.'),
('0DD', 'User heals by 1/2 damage dealt.'),
('0DE', 'User heals by 1/2 damage dealt. Fails if target is not asleep.'),
('0DF', 'Target heals by 1/2 max HP.'),
('0E0', 'User faints.'),
('0E1', 'Deals fixed damage to user''s current HP. User faints.'),
('0E2', 'Decreases target''s Attack and Special Attack by 2 stages. User faints.'),
('0E3', 'User faints and fully heals replacement (HP and status).'),
('0E4', 'User faints and fully heals replacement (HP, PP and status).'),
('0E5', 'Inflicts a temporary status condition to all Pokémon on the field which will make them faint in 3 turns.'),
('0E6', 'If user faints before their next move, the attack that caused it loses all of its PP.'),
('0E7', 'If user faints before their next move, the Pokémon that caused it also faints.'),
('0E8', 'If user would faint this turn, they survive with 1 HP instead.'),
('0E9', 'If target would faint from the hit, they survive with 1 HP instead.'),
('0EA', 'User flees.'),
('0EB', 'Target flees or switches out if not at higher level than user (status move).'),
('0EC', 'Target flees or switches out if not at higher level than user (damaging move).'),
('0ED', 'User switches out but passes on stat changes and temporary status conditions to their replacement.'),
('0EE', 'User switches out after dealing damage, even if trapped.'),
('0EF', 'Traps target as long as user remains on field.'),
('0F0', 'Removes target''s held item.'),
('0F1', 'Steals target''s held item.'),
('0F2', 'Swaps user''s and target''s held items.'),
('0F3', 'Gives held item to target.'),
('0F4', 'Consumes target''s berry, granting its effect to the user.'),
('0F5', 'Destroys target''s berry.'),
('0F6', 'User regains the last held item they consumed.'),
('0F7', 'Flings held item at the target, with power and effect depending on the item.'),
('0F8', 'Adds a temporary status condition to the target which negates the effect of their held item and prevents them from using the held item or having an item used on them.'),
('0F9', 'Adds an effect to both sides of the field which negates the effect of held items and prevents their use.'),
('0FA', 'Inflicts recoil damage on user equal to 1/4 damage dealt.'),
('0FB', 'Inflicts recoil damage on user equal to 1/3 damage dealt.'),
('0FC', 'Inflicts recoil damage on user equal to 1/2 damage dealt.'),
('0FD', 'Inflicts recoil damage on user equal to 1/3 damage dealt. Inflicts paralysis.'),
('0FE', 'Inflicts recoil damage on user equal to 1/3 damage dealt. Inflicts burn.'),
('0FF', 'Makes the weather sunny.'),
('100', 'Makes the weather rainy.'),
('101', 'Starts a sandstorm.'),
('102', 'Starts hail.'),
('103', 'Lays Spikes on the opposing side.'),
('104', 'Lays Toxic Spikes on the opposing side.'),
('105', 'Lays Stealth Rock on the opposjng side.'),
('106', 'Grass Pledge'),
('107', 'Fire Pledge'),
('108', 'Water Pledge'),
('109', 'Pay Day'),
('10A', 'Destroys barriers on target''s side of the field.'),
('10B', 'User is damaged by 1/2 max HP if this move misses.'),
('10C', 'Substitute'),
('10D', 'Curse'),
('10E', 'Removes 4 PP from last move used by target.'),
('10F', 'Inflcits a temporary status condition on the target that removes 1/4 of their max HP per turn, but only while they are asleep.'),
('110', 'Removes traps, entry hazards and Leech Seed from user and user''s side.'),
('111', 'Hits 2 turns later; user can still move meanwhile.'),
('112', 'Adds a stockpile.'),
('113', 'Power depends on the user''s stockpile level, which is reset to 0.'),
('114', 'Heals user for amount depending on their stockpile level, which is reset to 0.'),
('115', 'Only hits if user is not hit by a damaging move this turn.'),
('116', 'Only hits if target has not already moved this turn and has chosen a damaging move.'),
('117', 'For the duration of the current turn, any single-target moves will hit the user.'),
('118', 'Adds gravity to the field.'),
('119', 'Makes user airborne temporarily.'),
('11A', 'Makes user airborne, but also makes all attacks against them never miss.'),
('11B', 'Hits targets using Fly, Bounce or Sky Drop.'),
('11C', 'Grounds the target. Hits targets using Fly, Bounce or Sky Drop, and cancels Fly or Bounce.'),
('11D', 'Makes target move immediately after the user.'),
('11E', 'Makes target move last this turn.'),
('11F', 'Trick Room'),
('120', 'Ally Switch'),
('121', 'Use target''s Attack rather than user''s.'),
('122', 'Use target''s Defense rather than its Special Defense.'),
('123', 'Only damages Pokémon that share a type with the user.'),
('124', 'Wonder Room'),
('125', 'Fails unless user has used every other move it knows.'),
('133', 'King''s Shield'),
('134', 'Electric Terrain'),
('135', 'Grassy Terrain'),
('136', 'Misty Terrain'),
('137', 'Flying Press'),
('138', 'Decreases target''s Attack and Special Attack by 1 stage.'),
('139', 'Heals user for 0.75x damage dealt.'),
('140', 'Spiky Shield'),
('13A', 'Increases target''s Special Defense by 1 stage.'),
('13B', 'Decreases target''s Special Attack by 2 stages.'),
('13C', 'Belch'),
('13D', 'Parting Shot'),
('13E', 'Geomancy'),
('13F', 'Venom Drench'),
('142', 'Topsy-Turvy'),
('143', 'Forest''s Curse'),
('144', 'Trick or Treat'),
('145', 'Fairy Lock'),
('146', 'Magnetic Flux'),
('148', 'Ion Deluge'),
('149', 'Crafty Shield'),
('150', 'Flower Shield'),
('151', 'Rototiller'),
('152', 'Powder'),
('153', 'Electrify'),
('154', 'Mat Block'),
('155', 'Thousand Waves'),
('156', 'Thousand Arrows NOT USED'),
('157', 'Hyperspace Hole'),
('158', 'Oblivion Wing NOT USED'),
('159', 'Hyperspace Fury'),
('15A', 'Dummy'),
('15B', 'Aurora Veil'),
('15C', 'Baneful Bunker'),
('15D', 'Beak Blast'),
('15E', 'Burn Up'),
('15F', 'Spread move'),
('160', 'Core Enforcer'),
('161', 'First Impression'),
('162', 'Floral Healing'),
('163', 'Gear Up'),
('164', 'Instruct'),
('165', 'Laser Focus'),
('166', 'Sunsteel Strike/Moongeist Beam'),
('167', 'Pollen Puff'),
('168', 'Psychic Terrain'),
('169', 'Purify'),
('16A', 'RevelationDance'),
('16B', 'Shell Trap'),
('16C', 'Shore Up'),
('16D', 'Sparkling Aria'),
('16E', 'Spectral Thief'),
('16F', 'Speed Swap'),
('170', 'Spotlight'),
('171', 'Stomping Tantrum'),
('172', 'Strength Sap'),
('173', 'Throat Chop'),
('174', 'Toxic Thread'),
('175', 'Mind Blown'),
('176', 'Photon Geyser'),
('177', 'Plasma Fists'),
('178', 'Dynamax Cannon'),
('179', 'Snipe Shot'),
('17A', 'Stuff Cheeks'),
('17B', 'No Retreat'),
('17C', 'Tar Shot'),
('17D', 'Magic Powder'),
('17E', 'Dragon Darts'),
('17F', 'Teatime'),
('180', 'Octolock'),
('181', 'Fishious Rend'),
('182', 'Court Change'),
('183', 'Clangorous Soul'),
('184', 'Body Press'),
('185', 'Decorate'),
('186', 'Aura Wheel'),
('187', 'Life Dew'),
('188', 'Obstruct');
