-- can't be bothered doing this for now
-- todo later maybe

create table "mapname" ("map" integer primary key, "name" text);
insert into "mapname" ("map", "name")
values
(51, 'Intro'),
(689, 'Intro Desert'),
(667, 'Intro Train'),
(24, 'Reborn'),
(28, 'Reborn City (pre-restoration)'),
(29, 'Opal Ward (pre-restoration)'),
(38, 'Grand Hall 1F'),
(39, 'Grand Hall 2F'),
(764, 'Grand Hall B1F'),
(323, 'Grand Hall B1F - Bottom Left Room'),
(901, 'Grand Hall SEEKRIT Room')
(40, 'Opal Ward (pre-restoration, under bridge)'),
(467, 'Water Treatment Center'),
(470, 'North Obsidia Water Grid (dirty, low water)'),
(479, 'North Obsidia Water Grid (clean, low water)'),
(480, 'North Obsidia Water Grid (dirty, high water)'),
(497, 'North Obsidia Water Grid (clean, high water'),
(469, 'Central Obsidia Water Grid (dirty, low water)'),
(481, 'Central Obsidia Water Grid (clean, low water)'),
(498, 'Central Obsidia Water Grid (dirty, high water)'),
(448, 'Central Obsidia Water Grid (clean, high water'),
(471, 'Onyx Water Grid (dirty, low water)'),
(483, 'Onyx Water Grid (clean, low water)'),
(494, 'Onyx Water Grid (dirty, high water)'),
(499, 'Onyx Water Grid (clean, high water'),
(472, 'Coral Water Grid (dirty, low water)'),
(485, 'Coral Water Grid (clean, low water)'),
(486, 'Coral Water Grid (dirty, high water)'),
(500, 'Coral Water Grid (clean, high water'),
(473, 'Opal Water Grid (dirty, low water)'),
(487, 'Opal Water Grid (clean, low water)'),
(488, 'Opal Water Grid (dirty, high water)'),
(501, 'Opal Water Grid (clean, high water'),
(474, 'Peridot Water Grid (dirty, low water)'),
(489, 'Peridot Water Grid (clean, low water)'),
(490, 'Peridot Water Grid (dirty, high water)'),
(502, 'Peridot Water Grid (clean, high water'),
(475, 'Jasper Water Grid (dirty, low water)'),
(493, 'Jasper Water Grid (clean, low water)'),
(494, 'Jasper Water Grid (dirty, high water)'),
(504, 'Jasper Water Grid (clean, high water'),
(476, 'Beryl Water Grid (dirty, low water)'),
(495, 'Beryl Water Grid (clean, low water)'),
(496, 'Beryl Water Grid (dirty, high water)'),
(505, 'Beryl Water Grid (clean, high water'),
(478, 'Water Treatment Center - Holding Room'),
(477, 'Water Treatment Center - Gift Room'),
(606, 'GUM Room'),
(36, 'Obsidia Ward')
(1, 'Department Store 5F'),
(2, 'Department Store 6F'),
(3, 'Department Store 7F'),
(4, 'Department Store 8F'),
(5, 'Department Store 9F'),
(6, 'Department Store 11F'),
(7, 'Department Store 10F'),
(8, 'Blacksteam Factory 3F'),
(9, 'Blacksteam Factory 2F'),
(10, 'Blacksteam Factory 1F'),
(11, 'Blacksteam Factory B1F'),
(12, 'Blacksteam Factory B2F'),
(13, 'Blacksteam Factory 1F - PULSE Room'),
(14, 'Coral Ward (pre-restoration)'),
(15, 'Apophyll Beach - East'),
(16, 'Apophyll Beach - Central'),
(17, 'Apophyll Academy - Outer'),
(18, 'Apophyll Beach - North'),
(19, 'Apophyll Beach - West'),
(20, 'Apophyll Beach - Northwest'),
(21, 'Pyrous Mountain - Entrance'),
(22, 'Apophyll Academy - Front'),
(25, 'Apophyll Academy - Back'),
(26, 'Apophyll Academy - Kiki''s Room'),
(27, 'Pyrous Mountain - Summit'),
(30, 'Apophyll Cave 1F'),
(31, 'Apophyll Cave 2F'),
(33, 'Pyrous Mountain 1F - No Lava'),
(34, 'Pyrous Mountain 1F - Lava'),
(35, 'Pyrous Mountain B1F - No Lava'),
(200, 'Pyrous Mountain B2F'),
(201, 'Pyrous Mountain 2F - No Lava'),
(202, 'Pyrous Mountain 2F - Lava'),
(203, 'Pyrous Mountain 3F - No Lava'),
(204, 'Pyrous Mountain 3F - Lava'),
(205, 'Pyrous Mountain 4F'),
(206, 'Azurine Island (pre-restoration)'),
(887, 'New World Helix 1'),
(888, 'New World Helix 2'),
(199, 'Pyrous Mountain B1F - Lava'),
